#!/bin/bash

clear
echo -e " [1] Create"
echo -e " [2] Create Random"
echo -e " [3] Create Trial"
echo -e " [4] User List"
echo -e " [5] User Details"
echo -e " [6] User Extend"
echo -e " [7] User Delete"
echo -e " [8] User Lock"
echo -e " [9] User Unlock"
echo -e " [10] Connections"
echo -e " [11] Delete Expired"
echo -e " [12] Locked List"
echo -e " [13] Exit/Cancel"
echo -e ""
read -p " Select from options [1-13]: " Accounts
echo -e "\n\n"
sleep 1
clear
case $Accounts in
		1)
		clear
		create
		exit
		;;
		2)
		clear
		create_random
		exit
		;;
		3)
		clear
		create_trial
		exit
		;;
		4)
		clear
		user_list
		exit
		;;
		5)
		clear
		user_details
		exit
		;;
		6)
		clear
		user_extend
		exit
		;;
		7)
		clear
		user_delete
		exit
		;;
		8)
		clear
		user_lock
		exit
		;;
		9)
		clear
		user_unlock
		exit
		;;
		10)
		clear
		connections
		exit
		;;
		11)
		clear
		delete_expired
		exit
		;;
		12)
		clear
		locked_list
		exit
		;;
		13)
		clear
		exit
		;;
	esac
