#!/bin/bash
clear

echo -e ""
echo -e " PisoVPN "
echo -e " Create Account"
echo -e ""
read -p "  Username: " User

# Check If Username Exist, Else Proceed
egrep "^$User" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
clear
echo -e ""
echo -e " PisoVPN "
echo -e " Username Already Exists on your server, please try another username"
exit 0
else
read -p "  Password: " Pass
read -p "  Active Days: " Days
echo -e ""
echo -e ""
clear
sleep 1
MYIP=$(wget -qO- ipv4.icanhazip.com)
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g' )"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
squidport="$(cat /etc/privoxy/config | grep -i listen-address | awk '{print $2}' | xargs | sed -e 's/ /, /g')"
useradd -m -s /bin/false -e $Expiration $User > /dev/null
egrep "^$User" /etc/passwd &> /dev/null
echo -e "$Pass\n$Pass\n" | passwd $User &> /dev/null
clear
echo -e ""
echo -e " PisoVPN " 
echo -e " Your Account:"
echo -e "  Username: $User"
echo -e "  Password: $Pass"
echo -e "  Account Expiry: $Expiration_Display"
echo -e ""
echo -e "  Host/IP: "$MYIP
echo -e "  OpenSSH Port: "$opensshport
echo -e "  Dropbear Port: "$dropbearport
echo -e "  SSL Port: "$stunnel4port
echo -e "  Proxy Ports: "$squidport
echo -e "  OpenVPN Port: "$openvpnport
echo -e ""
echo -e ""
fi
