#!/bin/bash

MYIP=$(wget -qO- ipv4.icanhazip.com)
User=trial`</dev/urandom tr -dc X-Z0-9 | head -c4`
Pass=`</dev/urandom tr -dc a-f0-9 | head -c9`

# Trial Account Expiration Day/s
Days="1"

Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g' )"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
squidport="$(cat /etc/privoxy/config | grep -i listen-address | awk '{print $2}' | xargs | sed -e 's/ /, /g')"

useradd -e `date -d "$Days days" +"%Y-%m-%d"` -s /bin/false -M $User &> /dev/null
echo -e "$Pass\n$Pass\n"|passwd $User &> /dev/null
clear
echo -e ""
echo -e " PisoVPN "
echo -e " Trial Account"
echo -e "   IP Address: "$MYIP
echo -e "   Username: $User"
echo -e "   Password: $Pass"
echo -e "   Account Expiry: $Expiration_Display"
echo -e ""
echo -e "   OpenSSH Port: "$opensshport
echo -e "   Dropbear Port: "$dropbearport
echo -e "   SSL Port: "$stunnel4port
echo -e "   Proxy Ports: "$squidport
echo -e "   OpenVPN Port: "$openvpnport
echo -e ""
echo -e ""
