#!/bin/bash
# Script by : _Dreyannz_
rm -f /root/opensshport
rm -f /root/dropbearport
rm -f /root/stunnel4port
rm -f /root/openvpnport
rm -f /root/squidport
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
squidport="$(cat /etc/squid3/squid.conf | grep -i listen-address | awk '{print $2}')"
echo $opensshport > /root/opensshport
cat > /root/opensshport <<-END
$opensshport
END
echo $dropbearport > /root/dropbearport
cat > /root/dropbearport <<-END
$dropbearport
END
echo $stunnel4port > /root/stunnel4port
cat > /root/stunnel4port <<-END
$stunnel4port
END
echo $openvpnport > /root/openvpnport
cat > /root/openvpnport <<-END
$openvpnport
END
echo $squidport > /root/squidport
cat > /root/squidport <<-END
$squidport
END

cd
clear
echo -e ""
echo -e " PisoVPN "
echo -e " Squid3 Ports: $squidport"
echo -e ""
read -p " Which port should be changed?: " Port
egrep "^$Port" /root/squidport >/dev/null
if [ $? -eq 0 ]; then
	read -p " From Port $Port -> Port?: " Port_New
	if grep -Fxq $Port_New /root/opensshport; then
		echo -e ""
		echo -e " OpenSSH Port Conflict"
		echo -e " Port Is Already In Use"
		echo -e ""
		exit
	fi
	if grep -Fxq $Port_New /root/dropbearport; then
		echo -e ""
		echo -e " Dropbear Port Conflict"
		echo -e " Port Is Already In Use"
		echo -e ""
		exit
	fi
	if grep -Fxq $Port_New /root/stunnel4port; then
		echo -e ""
		echo -e " Stunnel4 Port Conflict"
		echo -e " Port Is Already In Use              "
		echo -e ""
		exit
	fi
	if grep -Fxq $Port_New /root/openvpnport; then
		echo -e ""
		echo -e " OpenVPN Port Conflict"
		echo -e " Port Is Already In Use"
		echo -e ""
		exit
	fi
	Port_Change="s/$Port/$Port_New/g";
	sed -i $Port_Change /etc/privoxy/config
	service squid restart > /dev/null
	rm -f /root/squidport
	squidport="$(cat /etc/privoxy/config | grep -i listen-address | awk '{print $2}')"
	clear
	echo -e ""
echo -e " PisoVPN "
  echo -e " Successfully Reconfigured"
	echo -e " your Squid Port is now: $squidport"
	echo -e ""

else
	echo -e ""
	echo -e " Port you entered does not"
  echo -e " exist in Squid config"
  echo -e " exiting..."
	echo -e ""
fi
