#!/bin/bash

clear
echo -e ""
echo -e " PisoVPN "
echo -e ""
echo -e "  [1] Show All Service Ports"
echo -e "  [2] Edit OpenSSH Port"
echo -e "  [3] Edit Dropbear Port"
echo -e "  [4] Edit Stunnel Port"
echo -e "  [5] Edit Port OpenVPN"
echo -e "  [6] Edit Port Squid"
echo -e "  [7] Exit"
echo -e ""
read -p "  Select From Options [1-7]: " Port
echo -e ""
sleep 2
clear
case $Port in
			1)
			clear
			show_ports
			exit
			;;
			2)
			clear
			edit_openssh
			exit
			;;
			3)
			clear
			edit_dropbear
			exit
			;;
			4)
			clear
			edit_stunnel4
			exit
			;;
			5)
			clear
			edit_openvpn
			exit
			;;
			6)
			clear
			edit_squid3
			exit
			;;
			7)
			clear
			exit
			;;
	esac
