#!/bin/bash

clear
echo -e ""
echo -e " PisoVPN " | lolcat -a
echo -e ""
echo -e "   [1] Reboot Now"
echo -e "   [2] Reboot Time"
echo -e "   [3] Exit"
echo -e ""
read -p "   Select from options [1-3]: " Reboot
echo -e ""
sleep 3
clear
case $Reboot in
		1)
		clear
		reboot
		exit
		;;
		2)
		clear
		reboot_sys_auto
		exit
		;;
		3)
		clear
		exit
		;;
	esac