#!/bin/bash

clear
echo -e ""
echo -e " PisoVPN " | lolcat -a
echo -e ""
echo -e "   [1] Reboot Every 1 Hour"
echo -e "   [2] Reboot Every 2 Hours"
echo -e "   [3] Reboot Every 12 Hours"
echo -e "   [4] Reboot Once A Day"
echo -e "   [5] Reboot Once A Week"
echo -e "   [6] Reboot Once A Month"
echo -e "   [7] Remove Reboot"
echo -e "   [8] Exit"
echo -e ""
read -p "   Select from options [1-8]:  " Reboot_Sys
echo -e ""

sleep 3
clear
case $Reboot_Sys in
		1)
		clear
		echo "10 * * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
    echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
    echo -e " Auto-Reboot Set Every Hour"
    echo -e ""
    exit
    ;;
		2)
		clear
		echo "10 */6 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
    echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Auto-Reboot Set Every 2 Hours"
		echo -e ""
		exit
		;;
		3)
		clear
		echo "10 */12 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Auto-Reboot Set Every 12 Hours"
		echo -e ""
		exit
		;;
		4)
		clear
		echo "10 0 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Auto-Reboot Set Once A Day"
		echo -e ""
		exit
		;;
		5)
		clear
		echo "10 0 */7 * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Auto-Reboot Set Once A Week"
		echo -e ""
		exit
		;;
		6)
		clear
		echo "10 0 1 * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Auto-Reboot Set Once A Month"
		echo -e ""
		exit
		;;
		7)
		clear
		rm -f /etc/cron.d/reboot_sys
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Auto-Reboot Removed"
		echo -e ""
		exit
		;;
		8)
		clear
		exit
		;;
	esac
service cron restart