#!/bin/bash

clear
echo -e ""
echo -e " PisoVPN " | lolcat -a
echo -e ""
echo -e "   [1] AutoKill After 5 Minutes"
echo -e "   [2] AutoKill After 15 Minutes"
echo -e "   [3] AutoKill After 30 Minutes"
echo -e "   [4] Turn Off AutoKill/MultiLogin"
echo -e "   [5] Exit"
echo -e ""
read -p "   Select from options [1-5]: " AutoKill
echo -e ""
case $AutoKill in
		1)
		read -p " Allowed MultiLogin: " -e -i 1 MultiLogin
		echo -e ""
		sleep 2
		clear
		echo "*/5 * * * *  root /usr/bin/set_multilogin_autokill_lib $MultiLogin" > /etc/cron.d/set_multilogin_autokill_lib
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Allowed MultiLogin: $MultiLogin"
		echo -e " AutoKill Every: 5 Minutes"
		echo -e ""
		exit
		;;
		2)
		read -p " Allowed MultiLogin: " -e -i 1 MultiLogin
		echo -e ""
		sleep 2
		clear
		echo "*/15 * * * *  root /usr/bin/set_multilogin_autokill_lib $MultiLogin" > /etc/cron.d/set_multilogin_autokill_lib
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Allowed MultiLogin: $MultiLogin"
		echo -e " AutoKill Every: 15 Minutes"
		echo -e ""
		exit
		;;
		3)
		read -p " Allowed MultiLogin: " -e -i 1 MultiLogin
		echo -e ""
		sleep 2
		clear
		echo "*/30 * * * *  root /usr/bin/set_multilogin_autokill_lib $MultiLogin" > /etc/cron.d/set_multilogin_autokill_lib
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " Allowed MultiLogin: $MultiLogin"
		echo -e " AutoKill Every: 30 Minutes"
		echo -e ""
		exit
		;;
		4)
		clear
		rm -f /etc/cron.d/set_multilogin_autokill_lib
		echo -e ""
    echo -e " PisoVPN " | lolcat -a
    echo -e ""
		echo -e " AutoKill MultiLogin Turned Off"
		echo -e ""
		exit
		;;
		5)
		clear
		exit
		;;
	esac
service cron restart