#!/bin/bash

clear
echo -e ""
echo -e " PisoVPN " | lolcat -a
echo -e ""
read -p " Username: " User
egrep "^$User" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
sleep 1
if grep -Fxq "$User" /etc/Locked_List.txt
then
  clear
echo -e ""
echo -e " PisoVPN " | lolcat -a
echo -e ""
echo -e " User Has Been Unlocked"
echo -e " User Has Been Removed from Locked_List"
echo -e ""
passwd -u $User
sed -i 's/$User//g' /etc/Locked_List.txt

exit
else
  clear
echo -e ""
echo -e " PisoVPN " | lolcat -a
echo -e ""
echo -e " User Is Not Locked"
echo -e ""

exit
fi

else
	clear
	echo -e ""
echo -e " PisoVPN " | lolcat -a
  echo -e ""
	echo -e " Username Doesnt Exist"
	echo -e ""
	exit
    exit 1
fi